// src/lib/states.ts
// Pure onboarding state metadata shared by server logic and client UI.

export const TRANSITIONS: Record<string, string[]> = {
  LEAD_RECEIVED: ['PACK_SENT'],
  PACK_SENT: ['DOCS_SUBMITTED'],
  DOCS_SUBMITTED: ['DOCS_PROCESSING'],
  DOCS_PROCESSING: ['DOCS_VALIDATED', 'DOCS_EXCEPTION'],
  DOCS_EXCEPTION: ['DOCS_PROCESSING'],
  DOCS_VALIDATED: ['HQ_PROFILE_CREATED'],
  HQ_PROFILE_CREATED: ['SAMSUB_SUBMITTED'],
  SAMSUB_SUBMITTED: ['SAMSUB_COMPLETE'],
  SAMSUB_COMPLETE: ['COMPLIANCE_REVIEW'],
  COMPLIANCE_REVIEW: ['COMPLIANCE_APPROVED', 'COMPLIANCE_EXCEPTION'],
  COMPLIANCE_EXCEPTION: ['SAMSUB_SUBMITTED'],
  COMPLIANCE_APPROVED: ['CONTRACT_DRAFT_REQUESTED'],
  CONTRACT_DRAFT_REQUESTED: ['CONTRACT_SENT'],
  CONTRACT_SENT: ['CLIENT_REVIEWING_CONTRACT'],
  CLIENT_REVIEWING_CONTRACT: ['CONTRACT_COMMENTS_RECEIVED', 'CONTRACT_ACCEPTED'],
  CONTRACT_COMMENTS_RECEIVED: ['LEGAL_REVIEW'],
  LEGAL_REVIEW: ['CONTRACT_REVISED_SENT'],
  CONTRACT_REVISED_SENT: ['CLIENT_REVIEWING_CONTRACT'],
  CONTRACT_ACCEPTED: ['SIGNATORIES_REQUESTED'],
  SIGNATORIES_REQUESTED: ['DOCSIGN_PENDING'],
  DOCSIGN_PENDING: ['DOCSIGN_SIGNED'],
  DOCSIGN_SIGNED: ['CONTRACT_UPLOADED_HQ'],
  CONTRACT_UPLOADED_HQ: ['USERS_REQUESTED'],
  USERS_REQUESTED: ['USERS_CREATED'],
  USERS_CREATED: ['CLIENT_ACTIVE'],
  CLIENT_ACTIVE: ['FIRST_TRADE_PENDING'],
  FIRST_TRADE_PENDING: ['TRADING'],
  TRADING: [],
}

export function getNextStates(state: string): string[] {
  return TRANSITIONS[state] ?? []
}
